_target_: functools.partial
_args_: 
  - ${get_method:torch.optim.lr_scheduler.ReduceLROnPlateau}
mode: "min"
factor: 0.5  # halving
patience: 20  # default: 20, val epochs; new: 60
cooldown: 5  # defatul: 5, val epochs; new: 10
verbose: true  # print when reducing LR