# https://www.comet.ml

comet:
  _target_: pytorch_lightning.loggers.comet.CometLogger
  api_key: ${oc.env:COMET_API_TOKEN} # api key is loaded from environment variable
  workspace: ${oc.env:COMET_WORKSPACE}
  project_name: "crossvalidation" #${oc.env:COMET_PROJECT_NAME}
  experiment_name: ??? # can be overrided at runtime
  auto_log_co2: false
  disabled: false
